version: '3'
services:
  saml:
    image: kristophjunge/test-saml-idp
    ports:
    - "8080:8080"
    - "8443:8443"
    environment:
    - SIMPLESAMLPHP_SP_ENTITY_ID=http://app.example.com
    - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://localhost/simplesaml/module.php/saml/sp/saml2-acs.php/test-sp
    - SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE=http://localhost/simplesaml/module.php/saml/sp/saml2-logout.php/test-sp
#    volumes:
#    - ./users.php:/var/www/simplesamlphp/config/authsources.php